-- Laboratory Module Tables
-- laboratory_templates: test shablonlari (maydonlar, normallar, birliklar)
-- laboratory_tests: bemorga buyurilgan tahlillar va natijalar

CREATE TABLE IF NOT EXISTS laboratory_templates (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id   BIGINT NOT NULL DEFAULT get_clinic_id(),
  testName    TEXT NOT NULL,
  category    TEXT,
  price       REAL DEFAULT 0,
  fieldsJson  TEXT DEFAULT '[]',  -- JSON: [{name, type, unit, minM, maxM, minF, maxF, panicL, panicH, formula, options}]
  createdAt   TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE laboratory_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Clinic isolation" ON laboratory_templates;
CREATE POLICY "Clinic isolation" ON laboratory_templates
  FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS laboratory_tests (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id     BIGINT NOT NULL DEFAULT get_clinic_id(),
  patientId     BIGINT REFERENCES patients(id) ON DELETE SET NULL,
  testName      TEXT NOT NULL,
  laboratoryId  TEXT,                -- barcode/scan ID, e.g. "LAB-123456-42"
  isUrgent      INTEGER DEFAULT 0,
  status        TEXT DEFAULT 'pending', -- pending | sampled | processing | ready
  orderedBy     BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
  resultJson    TEXT DEFAULT '{}',   -- JSON: {fieldName: value}
  completedAt   TIMESTAMPTZ,
  createdAt     TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE laboratory_tests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Clinic isolation" ON laboratory_tests;
CREATE POLICY "Clinic isolation" ON laboratory_tests
  FOR ALL USING (clinic_id = get_clinic_id());

CREATE INDEX IF NOT EXISTS idx_laboratory_tests_clinic    ON laboratory_tests(clinic_id);
CREATE INDEX IF NOT EXISTS idx_laboratory_tests_patient   ON laboratory_tests(patientId);
CREATE INDEX IF NOT EXISTS idx_laboratory_tests_status    ON laboratory_tests(status);
CREATE INDEX IF NOT EXISTS idx_laboratory_templates_clinic ON laboratory_templates(clinic_id);
