-- Analytics Module: Doctor Payouts
-- Shifokor maoshlari va komissiya to'lovlari

CREATE TABLE IF NOT EXISTS doctor_payouts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id    BIGINT NOT NULL DEFAULT get_clinic_id(),
  doctor_id    BIGINT REFERENCES doctors(id) ON DELETE SET NULL,
  amount       REAL NOT NULL,
  percentage   REAL DEFAULT 0,     -- qaysi foiz hisobida berilgan (masalan 50%)
  period_type  TEXT DEFAULT 'day', -- day | week | month | custom
  note         TEXT DEFAULT '',
  createdAt    TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE doctor_payouts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Clinic isolation" ON doctor_payouts;
CREATE POLICY "Clinic isolation" ON doctor_payouts
  FOR ALL USING (clinic_id = get_clinic_id());

CREATE INDEX IF NOT EXISTS idx_doctor_payouts_clinic ON doctor_payouts(clinic_id);
CREATE INDEX IF NOT EXISTS idx_doctor_payouts_doctor ON doctor_payouts(doctor_id);
