-- Supabase SaaS SQL Schema (Multi-tenant with RLS)

-- 1. Helper function to get current user's clinic_id from JWT app_metadata
-- Reads from app_metadata (set by admin) not user_metadata (set by user)
-- Consistent with get_my_clinic_id() in tenant_auth migration
CREATE OR REPLACE FUNCTION get_clinic_id()
RETURNS BIGINT AS $$
  SELECT (auth.jwt() -> 'app_metadata' ->> 'clinic_id')::BIGINT;
$$ LANGUAGE sql STABLE;

---------------------------------------------------------
-- TABLES WITH CLINIC_ID AND RLS
---------------------------------------------------------

CREATE TABLE IF NOT EXISTS clinics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  owner_id UUID,
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE clinics ENABLE ROW LEVEL SECURITY;
-- No policy here yet as it's the base table

CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  fullName TEXT NOT NULL,
  phone TEXT,
  birthDate TEXT,
  gender TEXT,
  address TEXT,
  source TEXT DEFAULT '',
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON patients FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  fullName TEXT NOT NULL,
  specialty TEXT,
  prefix TEXT,
  phone TEXT,
  role TEXT DEFAULT 'doctor',
  isActive INTEGER DEFAULT 1,
  commission_rate REAL DEFAULT 0,
  commission_fixed TEXT DEFAULT '0',
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE doctors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON doctors FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  name TEXT NOT NULL,
  price REAL NOT NULL,
  category TEXT,
  duration INTEGER,
  isActive INTEGER DEFAULT 1,
  orderIndex INTEGER DEFAULT 0
);
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON services FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  patientId BIGINT REFERENCES patients(id),
  doctorId BIGINT REFERENCES doctors(id),
  serviceId BIGINT REFERENCES services(id),
  status TEXT DEFAULT 'pending',
  paymentType TEXT,
  amount REAL,
  discount REAL DEFAULT 0,
  quantity INTEGER DEFAULT 1,
  queueNumber TEXT,
  notes TEXT,
  shift_id BIGINT,
  createdBy TEXT,
  commissionPaid INTEGER DEFAULT 0,
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON appointments FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  appointmentId BIGINT REFERENCES appointments(id),
  doctorId BIGINT REFERENCES doctors(id),
  patientId BIGINT REFERENCES patients(id),
  number INTEGER,
  prefix TEXT,
  status TEXT DEFAULT 'waiting',
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON queue FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  name TEXT NOT NULL,
  department TEXT,
  floor INTEGER,
  capacity INTEGER DEFAULT 2,
  type TEXT DEFAULT 'shared',
  pricePerDay REAL,
  mealPrice REAL DEFAULT 0,
  cleaningStatus TEXT DEFAULT 'clean',
  isActive INTEGER DEFAULT 1
);
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON rooms FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS room_tariffs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  roomId BIGINT REFERENCES rooms(id),
  name TEXT NOT NULL,
  pricePerDay REAL NOT NULL
);
ALTER TABLE room_tariffs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON room_tariffs FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS room_patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  roomId BIGINT REFERENCES rooms(id),
  patientId BIGINT REFERENCES patients(id),
  doctorId BIGINT REFERENCES doctors(id),
  tariffId BIGINT REFERENCES room_tariffs(id),
  entryDate TIMESTAMPTZ DEFAULT now(),
  exitDate TIMESTAMPTZ,
  days INTEGER,
  totalCost REAL,
  status TEXT DEFAULT 'active',
  age INTEGER,
  gender TEXT,
  phone TEXT,
  notes TEXT,
  hasMeals INTEGER DEFAULT 0,
  dietType TEXT DEFAULT 'standard',
  bedIndex TEXT,
  depositBalance REAL DEFAULT 0,
  lastChargeDate TEXT,
  arrivalTime TEXT,
  createdBy TEXT,
  commissionPaid INTEGER DEFAULT 0
);
ALTER TABLE room_patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON room_patients FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  appointmentId BIGINT,
  patientId BIGINT REFERENCES patients(id),
  patient_name TEXT,
  doctor_id BIGINT REFERENCES doctors(id),
  service_id BIGINT,
  type TEXT,
  amount REAL,
  paymentType TEXT,
  debt REAL,
  description TEXT,
  shift_id BIGINT,
  isArchived INTEGER DEFAULT 0,
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON transactions FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  category TEXT NOT NULL,
  amount REAL NOT NULL,
  description TEXT,
  expenseDate TIMESTAMPTZ DEFAULT now(),
  createdAt TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON expenses FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS settings (
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  key TEXT,
  value TEXT,
  PRIMARY KEY (clinic_id, key)
);
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON settings FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  type TEXT,
  startTime TIMESTAMPTZ DEFAULT now(),
  endTime TIMESTAMPTZ,
  totalCash REAL DEFAULT 0,
  totalCard REAL DEFAULT 0,
  totalTransfer REAL DEFAULT 0,
  totalDebt REAL DEFAULT 0,
  totalDiscount REAL DEFAULT 0,
  status TEXT DEFAULT 'active'
);
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON shifts FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  fullName TEXT NOT NULL,
  role TEXT,
  phone TEXT,
  address TEXT,
  salary REAL,
  hiredAt TEXT,
  isActive INTEGER DEFAULT 1,
  auth_user_id UUID
);
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON staff FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id BIGINT NOT NULL DEFAULT get_clinic_id(),
  staffId BIGINT REFERENCES staff(id),
  date TEXT,
  checkIn TEXT,
  checkOut TEXT,
  status TEXT
);
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Clinic isolation" ON attendance FOR ALL USING (clinic_id = get_clinic_id());

CREATE OR REPLACE VIEW v_journal AS
SELECT 
  'outpatient' as source,
  t.id, t.clinic_id, t.patientId, t.patient_name, t.amount, t.paymentType, t.createdAt,
  d.fullName as doctorName
FROM transactions t
LEFT JOIN doctors d ON t.doctor_id = d.id;
