-- =============================================================================
-- Marketing Campaigns table
-- Referenced in rls_remaining_tables but never created.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.marketing_campaigns (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id   BIGINT NOT NULL DEFAULT get_clinic_id(),
  name        TEXT   NOT NULL,
  type        TEXT   NOT NULL DEFAULT 'sms',
  "targetGroup" TEXT DEFAULT 'all',
  content     TEXT,
  status      TEXT   DEFAULT 'active',
  "startDate" TIMESTAMPTZ DEFAULT now(),
  "endDate"   TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.marketing_campaigns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Clinic isolation" ON public.marketing_campaigns;
CREATE POLICY "Clinic isolation" ON public.marketing_campaigns
  FOR ALL
  TO authenticated
  USING      (clinic_id = get_clinic_id())
  WITH CHECK (clinic_id = get_clinic_id());
