-- Inpatient Module Tables
-- inpatient_treatments: statsionar bemorlar uchun muolaja jadvali
-- vital_signs: bemor vital ko'rsatkichlari (harorat, qon bosimi, puls, vazn)

CREATE TABLE IF NOT EXISTS inpatient_treatments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id     BIGINT NOT NULL DEFAULT get_clinic_id(),
  roomPatientId BIGINT REFERENCES room_patients(id) ON DELETE CASCADE,
  title         TEXT NOT NULL,
  scheduledTime TEXT,              -- "09:00" formatda
  notes         TEXT DEFAULT '',
  isDone        INTEGER DEFAULT 0,
  doneAt        TIMESTAMPTZ,
  createdAt     TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE inpatient_treatments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Clinic isolation" ON inpatient_treatments;
CREATE POLICY "Clinic isolation" ON inpatient_treatments
  FOR ALL USING (clinic_id = get_clinic_id());

CREATE TABLE IF NOT EXISTS vital_signs (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id     BIGINT NOT NULL DEFAULT get_clinic_id(),
  roomPatientId BIGINT REFERENCES room_patients(id) ON DELETE CASCADE,
  temperature   REAL,              -- tana harorati (°C)
  bp            TEXT,              -- qon bosimi, masalan "120/80"
  pulse         INTEGER,           -- yurak urishi (bpm)
  weight        REAL,              -- vazn (kg)
  createdAt     TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE vital_signs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Clinic isolation" ON vital_signs;
CREATE POLICY "Clinic isolation" ON vital_signs
  FOR ALL USING (clinic_id = get_clinic_id());

CREATE INDEX IF NOT EXISTS idx_inpatient_treatments_clinic   ON inpatient_treatments(clinic_id);
CREATE INDEX IF NOT EXISTS idx_inpatient_treatments_rp       ON inpatient_treatments(roomPatientId);
CREATE INDEX IF NOT EXISTS idx_vital_signs_clinic            ON vital_signs(clinic_id);
CREATE INDEX IF NOT EXISTS idx_vital_signs_rp                ON vital_signs(roomPatientId);
